### ISSUE TITLE
Enums of type long throws error 

### ISSUE THREAD

**Issue by ashamandava** [xwipeoutx/EnumGenie#9]
Hi, 

   is this expected ? when we try to load enums of type long system throws exception.
   Please let me know if we can handle this scenario.. 
Thanks,
Asha Mandava

**Comment by xwipeoutx** [comment]
Hi @ashamandava ,

Thanks for the report - can you include a sample of a problematic enum and the exception/stack trace? Including your code generation code would also be helpful.

Thanks.

**Comment by ashamandava** [comment]
Hi @xwipeoutx 

  Thanks for your quick response please find below details. 
Script 
public static void ConvertEnumsToTypeScript()
        {
            var genie = new EnumGenie.EnumGenie()
                .SourceFrom.Assembly(typeof(CPDataContractClassKeys).Assembly)
                .FilterBy.Predicate(t => t != typeof(AvailableTestHttpMethod))
                .TransformBy.RenamingEnum(def => def.Name.Replace("StripThisOut", ""))
                .WriteTo.Console(cfg => cfg.TypeScript(ts => ts.Declaration().Description().Descriptor()))
                .WriteTo.File("./app/enums/enums.ts", cfg => cfg.TypeScript(ts => ts.Declaration()));

            genie.Write();
        }

Enums: 

 public enum AvailableAlertMessageType : long
    {
        None = 56576565,
        EmailHtml = 12654645646456, // Min
        EmailText = 34534534534,
        EmailSms = 435345345,
        Rss = 42795468,
        Sms = 3434348908, // Max
    }

Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error rendering template. Cannot get identifier 'Value'. Error: 12654645646456 is not a valid value for Int32.. Source path: ....... See Typewriter output for more detail.

**Comment by xwipeoutx** [comment]
Yeah I see the problem, I didn't actually know you could do that with enums.

One problem I foresee is precision of numbers in JavaScript - they're stored as 64 bit floating point numbers, not integral, so large numbers will lose digits.  

For example, put `793548328091516927 === 793548328091516928` into your console, and you will get `true`.

This will happen not only on generation of the long, but also in the JSON deserialization of your API response.

In any case, I'll look at adding the feature (if it doesn't cause any issues/overcomplication) but I'd discourage its use.
